### ISSUE TITLE
Build failure with Cordova 5.0.0

### ISSUE THREAD

**Issue by saurabhgupta050890** [Wizcorp/phonegap-plugin-wizUtils#15]
I tried to add this plugin to my Cordova application build with Cordova 5.0.0 and my failed with this 

error/platforms/android/src/jp/wizcorp/phonegap/plugin/wizUtilsPlugin/WizUtilsPlugin.java:33: error: incompatible types
        _webView = webView;
                   ^
  required: WebView
  found:    CordovaWebView

**Comment by sebalagos90** [comment]
try with _webView = (WebView) webView.getView();
