### PR TITLE
Solved problem with cordova 5.0 on Android Java file.

### LINKED ISSUE #15: Build failure with Cordova 5.0.0
I tried to add this plugin to my Cordova application build with Cordova 5.0.0 and my failed with this 

error/platforms/android/src/jp/wizcorp/phonegap/plugin/wizUtilsPlugin/WizUtilsPlugin.java:33: error: incompatible types
        _webView = webView;
                   ^
  required: WebView
  found:    CordovaWebView

### PR DESCRIPTION
**Pull request by sebalagos90**
Fixes #15

### CODE REVIEW

**Comment by jrouault** [comment]
Thanks for your PR! I expect this to break with previous versions of Cordova so I have to update the plugin's version.
